services:
  starter-example:
    tty: true
    container_name: starter-example
    image: starter-example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - starter

  starter-postgres:
    tty: true
    container_name: starter-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=starter
      - POSTGRES_USER=starter
      - POSTGRES_DB=starter
    volumes:
      - starter_postgres_data:/var/lib/postgresql/data
    networks:
      - starter

  starter-redis:
    tty: true
    container_name: starter-redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - starter_redis_data:/data
    networks:
      - starter

  starter-caddy:
    image: caddy:2.7.6-alpine
    tty: true
    container_name: starter-caddy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - starter_caddy_data:/data
      - starter_caddy_config:/config
    networks:
      - starter

volumes:
  starter_postgres_data:
  starter_redis_data:
  starter_caddy_data:
  starter_caddy_config:

networks:
  starter:
    name: starter
